### ISSUE TITLE
Resize event listener not cleared on unmount

### ISSUE THREAD

**Issue by tibotiber** [williamngan/react-pts-canvas#16]
Hi @williamngan, it seems that the listener for resize events is not removed when the component unmounts. The listener gets set in the main pts lib from this line:

https://github.com/williamngan/react-pts-canvas/blob/1b0d7e8e618b5b4069d0a812fe854502f6ae12df/src/index.js#L57-L60

From there it ends up here in pts:

https://github.com/williamngan/pts/blob/fdb8fd52b8f9d45bfe6a77d2bccd0bda72f9d86b/src/Canvas.ts#L173-L180

I think we could add a `componentWillUnmount` lifecycle method that calls `this.space.autoResize(false)`. Would that work?

But I also feel it would be better that pts handles this on its own by deregistering event handlers when the element is unmounted. I couldn't find anywhere that tracks unmounting though and not sure how to proceed. 

Happy to try to code that but I might need some pointers ;).

I can re-open this in the pts repo if that's more suitable.

**Comment by williamngan** [comment]
Hi @tibotiber - thanks for catching this. 

Pts currently doesn't remove listeners automatically when an element unmounts. It's probably worth adding to Pts if it doesn't add a lot of code/complexity. 

I'm also fine with fixing this in React only, since it's somewhat an edge case if users are not using Pts as React components.

What do you think?

**Comment by tibotiber** [comment]
Yes, I have never used Pts without React, I've just had a look at your demo repo and it's indeed a lot more intentional about what's registered, bound, etc - so users would expect to clear the listeners themselves I guess. Seems like solving this in React only is a good fit. I'll have a go at it.
